version: '3.3'
services:
  server:
    build: server
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOSTNAME: testdb
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 10000
    depends_on:
      - testdb
  testdb:
    # Use of a modified datbase in 'db'-folder.
    # See README.md for more information.
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpw #user name is: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: testdb
      

      
